

export type Plan = {
  id: string;
  name: string;
  price?: string;
  priceCats?: string;
  priceDogs?: string;
  description: string;
  features: string[];
  optional?: string;
  isMostChosen: boolean;
};


export const plans: Plan[] = [
  {
    id: "essencia",
    name: "Essência",
    priceCats: "R$ 280,00",
    priceDogs: "R$ 450,00",
    description: "Ideal para famílias que desejam uma homenagem simbólica e ecológica.",
    features: [
      "Cremação coletiva",
      "Certificado de óbito",
    ],
    optional: "(+R$ 98,00) Plantio de uma muda de árvore nativa ou frutífera no Memorial PET Estrela, usando as cinzas do pet.",
    isMostChosen: false,
  },
  {
    id: "harmonia",
    name: "Harmonia",
    price: "R$ 960,00",
    description: "Ideal para famílias que desejam uma homenagem simbólica e ecológica.",
    features: [
      "Cremação coletiva em compartimento separado",
      "Porta-retrato + moldura da patinha",
      "Certidão de óbito",
      "Plantio de árvore no Memorial PET Estrela com QR Code exclusivo",
    ],
    isMostChosen: true,
  },
  {
    id: "eternus",
    name: "Eternus",
    price: "R$ 1.190,00",
    description: "Indicado para famílias que desejam uma homenagem mais completa e personalizada.",
    features: [
        "Cremação coletiva em compartimento separado",
        "Porta-retrato + moldura da patinha",
        "Certidão de óbito",
        "Urna biodegradável entregue em casa ou plantio de árvore no Memorial PET Estrela",
        "Cartinha personalizada com foto do pet",
        "Preparação para velório simples"
    ],
    isMostChosen: false,
  },
];

export const testimonials = [
  {
    name: "Ana Silva",
    petName: "Tutora do Max",
    quote: "O cuidado e o respeito que a Pet Estrela teve com a despedida do meu Max foi incrível. O memorial online é uma linda forma de sempre lembrar dele.",
    imageId: "testimonial-1",
  },
  {
    name: "Carlos Pereira",
    petName: "Tutor da Bella",
    quote: "Em um momento tão difícil, a equipe foi extremamente atenciosa e profissional. O processo foi tranquilo e a homenagem com o plantio da árvore nos confortou muito.",
    imageId: "testimonial-2",
  },
  {
    name: "Juliana Costa",
    petName: "Tutora do Simba",
    quote: "Serviço impecável. A sala de velório nos deu um momento de paz para nos despedirmos. A urna biodegradável foi uma escolha que combinou com nosso amor pela natureza.",
    imageId: "testimonial-3",
  },
  {
    name: "Marcos Andrade",
    petName: "Tutor do Pingo",
    quote: "Agradeço por toda a sensibilidade no momento mais difícil. O plantio da árvore em memória do Pingo foi um gesto que significou muito para nossa família.",
    imageId: "testimonial-4",
  },
  {
    name: "Fernanda Lima",
    petName: "Tutora da Nina",
    quote: "Nunca imaginei que a despedida da minha gatinha pudesse ser tão serena. Obrigada por transformarem a dor em uma bela homenagem.",
    imageId: "testimonial-5",
  },
  {
    name: "Lucas Martins",
    petName: "Tutor do Thor",
    quote: "O memorial online ficou lindo! É muito bom ter um lugar para visitar e lembrar dos bons momentos com nosso grande amigo.",
    imageId: "testimonial-6",
  },
  {
    name: "Beatriz Almeida",
    petName: "Tutora da Mel",
    quote: "A equipe foi de um profissionalismo e empatia sem igual. Recomendo de olhos fechados. Fizeram toda a diferença para nós.",
    imageId: "testimonial-7",
  },
  {
    name: "Rafael Oliveira",
    petName: "Tutor do Bob",
    quote: "Receber as cinzas do Bob em uma urna tão bonita e com o quadro da patinha foi muito reconfortante. Um trabalho feito com amor.",
    imageId: "testimonial-8",
  },
  {
    name: "Sofia Ribeiro",
    petName: "Tutora do Zeca",
    quote: "O atendimento 24h foi essencial, pois tudo aconteceu de madrugada. A agilidade e o acolhimento da equipe foram excepcionais. Só tenho a agradecer.",
    imageId: "testimonial-9",
  },
  {
    name: "Gabriel Ferreira",
    petName: "Tutor da Luna",
    quote: "A estrutura do local é incrível. Um ambiente de paz, que transmite tranquilidade. A cerimônia de despedida foi muito emocionante e respeitosa.",
    imageId: "testimonial-10",
  },
  {
    name: "Isabela Gomes",
    petName: "Tutora do Rocky",
    quote: "O plano Harmonia é muito completo. Cada detalhe, do porta-retrato à árvore plantada, mostra o carinho da empresa com nossa dor.",
    imageId: "testimonial-11",
  },
];

export const memorialPets = [
  {
    id: 1,
    name: "Luna",
    tutors: "Família Silva",
    animal: "Cão",
    sex: "Fêmea",
    breed: "Golden Retriever",
    birthDate: "2010-05-20",
    deathDate: "2023-10-15",
    memorialLocation: "Bosque da Serenidade, Ala Norte",
    tree: "Ipê Rosa",
    farewell: "Correu livre, deixou saudades e um amor que florescerá para sempre.",
    story: "Luna era a alegria da casa. Adorava buscar a bolinha no parque e deitar no pé do sofá para um cafuné. Seus olhos cor de mel e seu companheirismo eterno jamais serão esquecidos. Ela nos ensinou o verdadeiro significado do amor incondicional.",
    imageId: "memorial-1",
    galleryImageIds: ["memorial-gallery-luna-1", "memorial-gallery-luna-2", "memorial-gallery-luna-3", "memorial-gallery-luna-4", "memorial-1"],
  },
  {
    id: 2,
    name: "Thor",
    tutors: "Carlos Pereira",
    animal: "Gato",
    sex: "Macho",
    breed: "Siamês",
    birthDate: "2012-01-10",
    deathDate: "2023-11-02",
    memorialLocation: "Jardim do Silêncio, Seção B",
    tree: "Manacá da Serra",
    farewell: "Silencioso, mas de um amor imenso que ecoa em nossas memórias.",
    story: "Thor era um gato majestoso com um miado único que usava para pedir sachê. Gostava de observar o movimento da janela e dormir em caixas de papelão. Sua presença tranquila e seu olhar penetrante deixaram um vazio em nossos corações.",
    imageId: "memorial-2",
    galleryImageIds: ["memorial-gallery-thor-1", "memorial-gallery-thor-2", "memorial-gallery-thor-3", "memorial-gallery-thor-4", "memorial-2"],
  },
  {
    id: 3,
    name: "Mel",
    tutors: "Família Oliveira",
    animal: "Cão",
    sex: "Fêmea",
    breed: "Vira-lata",
    birthDate: "2013-08-01",
    deathDate: "2023-12-20",
    memorialLocation: "Campo das Lembranças, Fila 3",
    tree: "Quaresmeira",
    farewell: "Doce como o nome, eterna em nossos corações.",
    story: "Mel foi resgatada da rua e nos deu os melhores 10 anos de nossas vidas. Tinha um medo engraçado de trovão e um amor incondicional por biscoitos. Sua lealdade e doçura são um legado que guardaremos para sempre.",
    imageId: "memorial-3",
    galleryImageIds: ["memorial-gallery-mel-1", "memorial-gallery-mel-2", "memorial-gallery-mel-3", "memorial-gallery-mel-4", "memorial-3"],
  },
  {
    id: 4,
    name: "Bob",
    tutors: "Fernanda Lima",
    animal: "Cão",
    sex: "Macho",
    breed: "Pug",
    birthDate: "2015-02-14",
    deathDate: "2024-01-05",
    memorialLocation: "Bosque da Serenidade, Ala Sul",
    tree: "Pata de Vaca",
    farewell: "O roncador mais amado do mundo, agora dorme em paz.",
    story: "Bob e seus roncos preenchiam a casa de alegria. Era um cãozinho teimoso, engraçado e que amava um colo. Cada espirro e cada corrida desajeitada estão guardados na memória como momentos de pura felicidade.",
    imageId: "memorial-4",
    galleryImageIds: ["memorial-gallery-bob-1", "memorial-gallery-bob-2", "memorial-gallery-bob-3", "memorial-gallery-bob-4", "memorial-4"],
  },
  {
    id: 5,
    name: "Nina",
    tutors: "Roberto Santos",
    animal: "Gato",
    sex: "Fêmea",
    breed: "Persa",
    birthDate: "2011-11-30",
    deathDate: "2024-02-18",
    memorialLocation: "Jardim do Silêncio, Seção A",
    tree: "Cerejeira Ornamental",
    farewell: "Uma rainha em seu trono de almofadas, para sempre em nossa memória.",
    story: "Nina era a dona da casa. Com sua pelagem exuberante e seu jeito de rainha, ela comandava o ambiente. Amava ser escovada e só bebia água em seu copo particular. Uma dama que deixou um legado de elegância e muito amor.",
    imageId: "memorial-5",
    galleryImageIds: ["memorial-gallery-nina-1", "memorial-gallery-nina-2", "memorial-gallery-nina-3", "memorial-gallery-nina-4", "memorial-5"],
  },
  {
    id: 6,
    name: "Rocky",
    tutors: "Família Martins",
    animal: "Cão",
    sex: "Macho",
    breed: "Bulldog Francês",
    birthDate: "2018-07-25",
    deathDate: "2024-03-10",
    memorialLocation: "Campo das Lembranças, Fila 5",
    tree: "Jacarandá Mimoso",
    farewell: "Pequeno no tamanho, gigante no amor que deixou.",
    story: "Rocky era um poço de energia e alegria. Suas orelhas de morcego e seu sorriso eram contagiantes. Adorava brincar de cabo de guerra e tirar longas sonecas ao sol. Fará uma falta imensa.",
    imageId: "memorial-6",
    galleryImageIds: ["memorial-gallery-rocky-1", "memorial-gallery-rocky-2", "memorial-gallery-rocky-3", "memorial-gallery-rocky-4", "memorial-6"],
  },
  {
    id: 7,
    name: "Frida",
    tutors: "Beatriz Costa",
    animal: "Gato",
    sex: "Fêmea",
    breed: "Vira-lata",
    birthDate: "2019-03-12",
    deathDate: "2024-04-01",
    memorialLocation: "Jardim do Silêncio, Seção C",
    tree: "Sibipiruna",
    farewell: "Aventureira e carinhosa, sua memória floresce.",
    story: "Frida apareceu em nosso jardim e decidiu ficar. Era uma exploradora nata, sempre trazendo 'presentes' da rua. Seu espírito livre e seu ronronar alto nas noites frias são lembranças que aquecem nosso coração.",
    imageId: "memorial-7",
    galleryImageIds: ["memorial-gallery-frida-1", "memorial-gallery-frida-2", "memorial-gallery-frida-3", "memorial-gallery-frida-4", "memorial-7"],
  },
  {
    id: 8,
    name: "Zeca",
    tutors: "Lúcio Azevedo",
    animal: "Cão",
    sex: "Macho",
    breed: "Labrador",
    birthDate: "2014-09-09",
    deathDate: "2024-05-22",
    memorialLocation: "Bosque da Serenidade, Ala Leste",
    tree: "Jatobá",
    farewell: "O melhor amigo que alguém poderia ter. Corra livre, amigão.",
    story: "Zeca era a personificação da amizade. Sempre pronto para uma festa, um passeio ou simplesmente para deitar ao nosso lado. Sua partida deixou um silêncio que só as boas lembranças podem preencher. Adeus, amigão.",
    imageId: "memorial-8",
    galleryImageIds: ["memorial-gallery-zeca-1", "memorial-gallery-zeca-2", "memorial-gallery-zeca-3", "memorial-gallery-zeca-4", "memorial-8"],
  },
];
